spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadoLivro?createDatabaseIfNotExist=true
    username: root
    password: rootroot
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: c5022576-40bc-4272-a0d8-4ff27d5bdc2e
  expiration: 999999